name: Deploy to Hostinger
on:
  workflow_run:
    workflows: ["Laravel"]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git Pull
        run: ssh -p $HOSTINGER_SSH_PORT $HOSTINGER_SSH_USER@$HOSTINGER_SSH_IP 'cd ~/github/chat-gpt-laravel && git pull;'

      - name: Composer Install
        run: ssh -p $SSH_PORT $SSH_USER@$SSH_IP 'cd ~/github/chat-gpt-laravel && /opt/alt/php81/usr/bin/php ~/composer.phar install --no-dev --prefer-dist --no-ansi --no-interaction --no-progress;'
