name: Deploy to Hostinger
on:
  workflow_run:
    workflows: ["Laravel"]
    types:
      - completed
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git Pull
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: ssh -p $HOSTINGER_SSH_PORT $HOSTINGER_SSH_USER@$HOSTINGER_SSH_IP 'cd ~/github/chat-gpt-laravel && git pull;'
